### ISSUE TITLE
Do not compile a config where a nullary transformation is followed by a non-nullary one

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/ysv#23]
Example:

```yaml
version: 1
columns:
  something:
    - value: "boo"
    - input: "foo"
```

In this config, the `value` transformation is moot because it will be replaced by `input`.
