### ISSUE TITLE
Implement a transformation with if-else semantics

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/ysv#24]
### Example usecases:

* If the value is empty, replace it with value from variable (or hardcoded, or from another input column, or from another output column)
* If the value is equal to string "aaa", replace it with something else
* If the value is equal to variable named bbb, replace it with something else
* If the value matches "\d{2}" regex, prepend it with "000"

...and whatever. We need to come up with:

* syntax for that in the configuration file
* and an efficient implementation

**Comment by anatoly-scherbakov** [comment]
## Syntax 1

```yaml
version: 1
columns:
  phone:
    - input: phone
    - match?: "\d{10}"
    - prepend: "1"
    - else:
      - value: ""
```

If the phone number matches specified pattern, we preprend 1. Otherwise, we replace it with an empty value.

**Comment by anatoly-scherbakov** [comment]
## Syntax 2

```yaml
version: 1
columns:
  phone:
    - input: phone
    - if:
      conditon:
        - match: "\d{10}"
      then:
      - prepend: "1"
      - else:
        - value: ""
```

Kind of verbose.

**Comment by anatoly-scherbakov** [comment]
## Syntax 3

I am trying to express things monadically here.

```yaml
version: 1
columns:
  phone:
    - input: phone
    - match: "\d{10}"
    - map:
      - prepend: "1"
    - fix:
      - value: ""
```

I am afraid this is immensely verbose and will mean that every step in the algorithm must be tagged with a `map`, `fix` or something else.

I believe that, generally, every step in the transformations chain can be assumed to be a `.map()`. Is it not? How then to mark steps which are only executed when the value is an error?

**Comment by anatoly-scherbakov** [comment]
## Syntax 4 (impossible)

```yaml
version: 1
columns:
  phone:
    - input: phone
? - match: "\\d{10}"
:
 - then:
   - prepend: "1"
 - else:
   - value: ""
```

I tried to use the composite key syntax, but it only works at https://onlineyamltools.com/convert-yaml-to-json if the `?` has zero indentation level. This will not work.

**Comment by anatoly-scherbakov** [comment]
## Syntax 5 (actually 2 but improved)

```yaml
version: 1
columns:
  phone:
    - input: phone
    - match?:
      pattern: "\d{10}"
      then:
        - prepend: "1"
      else:
        - value: ""
```

This is less verbose, but more specialized than the `if - then - else` scenario. We are going to have multiple conditionals like this:

- `empty?`
- `equals?`
- `greater?`
- `less?`
- `positive?`
- `negative?`
- `zero?`

etc.

But this will also make the language more readable.

**Comment by anatoly-scherbakov** [comment]
## Syntax 6

```yaml
version: 1
columns:
  phone:
    - input: phone
    - if: {match: /\d{10}/}
      then: {prepend: "1"}
      else: {value: ""}
```

Shorthand syntax for a familiar `if .. then .. else` construct.
