### ISSUE TITLE
`input:` transformation has to support multiple arguments

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/ysv#27]
Example:

```yaml
version: 1
columns:
    first_name:
      - input:
        - First Name
        - FirstName
        - First
        - owner__first_name
```

The system has to check the first column which is present in the input file, and use that column as source.

If nothing is present, a warning is issued and the output column (in this case `first_name`) is going to be empty.

This is an important feature for many usecases where we need to convert diverse input data to some sort of standard form.
