### ISSUE TITLE
Construct a list of values

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/ysv#28]
Suppose we want to join two columns.

```yaml
version: 1
columns:
  full_name:
    - [
        input: title,
        input: first_name,
        input: last_name,
      ]
    - join: " "
```

We are facilitating the built-in YAML construct to make a list. I think this looks rather user-friendly.

**Comment by anatoly-scherbakov** [comment]
Support for lists allows us to use whole lot of list-oriented functions people are accustomed to. Examples:

```yaml
- join: ", "
- range: [0, 3]
- filter: unempty
- map: strip
- reverse
- first
- last
- max
- min
- average
```

**Comment by anatoly-scherbakov** [comment]
How do we construct a list where one of the items requires a more complicated expression?

```yaml
- [
    [
      - input: age
      - string
    ],
    value: "year(s)"
  ]
```

Something like this, I think.

**Comment by anatoly-scherbakov** [comment]
Now let's consider a real life example - splitting postal codes into two parts.

```yaml
columns:
  zipcode_split:
    - input: zip_code
    - strip
    - replace:
      "-": ""
    - split-by-index: 5
    - hide
  zip5:
    - from: zipcode_split
    - index: 0
  zip4:
    - from: zipcode_split
    - index: 1
```
