### ISSUE TITLE
Annotate the type of CSV cell value and provide date conversion transformations

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/ysv#29]
```yaml
version: 1
columns:
  event_date:
    - input: Date
    - date: %m/%d/%Y
    - date-to-string: %Y-%m-%d
```

**Comment by anatoly-scherbakov** [comment]
```yaml
date:
  - input: LastTransactionDate
  - date: %Y-%m-%d
```

This is the simplest possible way to parse a date I can think of. But what if the user wants, say,

* to replace with a default value
* or to skip the line
* or to stop processing?

I think that should be handled by other transformations. For example:

```
date:
  - input: LastTransactionDate
  - date: %Y-%m-%d
  - no-value?:
    - skip-line
    # or
    - crash
    # or
    - value: 2000-01-01
```
