### ISSUE TITLE
replace_regex: a regular expression causes YAML parsing error

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/ysv#41]
Code:

```yaml
    - replace_regex:
        pattern: "^(\d{4}-\d{2}-\d{2})"
        replace: $1
```

Error:

```
thread 'main' panicked at 'YAML config could not be parsed.: Scan(ScanError { mark: Marker { index: 176, line: 10, col: 17 }, info: "while parsing a quoted scalar, found unknown escape character" })', /home/anatoly/.cargo/registry/src/github.com-1ecc6299db9ec823/ysv-0.1.3/src/compile/mod.rs:27:8
```
