### ISSUE TITLE
Implement replace by file (list or mapping of values)

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/ysv#49]
```yaml
phone:
  - input: phone
  - replace_with_file:
    path: blacklist.txt
    value: ""
```
or something like that.
